# Gmail credentials
gmail:
  app:
    username: glenn.sabales@gmail.com
    password: uoqzlqdayewhqayb

# Email sending config
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail.app.username}
    password: ${gmail.app.password}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
